name: Maven Full Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Validate
      run: mvn validate

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Package
      run: mvn package

    - name: Verify
      run: mvn verify

    - name: Install
      run: mvn install

    - name: Site
      run: mvn site
